server.document-root = "/var/www/localhost/htdocs"
server.port = 80
#server.username = "root"
#server.groupname = "root"
server.errorlog = "/dev/stderr"
accesslog.filename = "/dev/stdout"

server.modules = (
  "mod_access",
  "mod_alias",
  "mod_compress",
  "mod_redirect",
  "mod_fastcgi"
)

index-file.names = ( "index.php", "index.html" )
mimetype.assign = (
  ".html" => "text/html",
  ".txt"  => "text/plain",
  ".css"  => "text/css",
  ".js"   => "application/javascript",
  ".json" => "application/json",
  ".png"  => "image/png",
  ".jpg"  => "image/jpeg",
  ".jpeg" => "image/jpeg",
  ".gif"  => "image/gif",
  ".svg"  => "image/svg+xml",
  ".php"  => "text/html"
)

fastcgi.server = (
  ".php" => ((
    "socket" => "/tmp/php-fcgi.sock",
    "bin-path" => "/usr/bin/php-cgi85",
    "max-procs" => 1,
    "bin-environment" => (
      "PHP_FCGI_CHILDREN" => "4",
      "PHP_FCGI_MAX_REQUESTS" => "1000"
    )
  ))
)
